on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: cd ./CollectThemAll
      - run: dotnet --version
      - run: dotnet build